version: '3'
services:

  # Mongo Database for the push notification
  # ========================================
  lexio-push-notification-mongo:
    container_name: lexio-push-notification-mongo
    image: lexio/lexio-push-notification-mongo:latest
    env_file: .env
    command: --auth
    build:
      context: ./lexio-push-notification-mongo
      args: # used by setup.js
        - mongoInitDbRootUsername=${MONGO_INITDB_ROOT_USERNAME}
        - mongoInitDbRootPassword=${MONGO_INITDB_ROOT_PASSWORD}
        - mongoApiPassword=${MONGO_API_PASSWORD}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - "27017"
    volumes:
      - /opt/lexio/prod/lexio-push-notification-mongo/db:/data/db

  # Microservice for the push notification
  # ======================================
  lexio-push-notification:
    container_name: lexio-push-notification
    build: ../lexio-push-notification
    image: lexio/lexio-push-notification:0.2.0
    environment:
      NODE_ENV: production
      MONGO_API_PASSWORD: ${MONGO_API_PASSWORD}
      API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "3010"
    links:
      - lexio-push-notification-mongo:mongohost

  # Mongo Database for the purchase
  # ===============================
  lexio-purchase-mongo:
    container_name: lexio-purchase-mongo
    image: lexio/lexio-purchase-mongo:latest
    env_file: .env
    command: --auth
    build:
      context: ./lexio-purchase-mongo
      args: # used by setup.js
        - mongoInitDbRootUsername=${MONGO_INITDB_ROOT_USERNAME}
        - mongoInitDbRootPassword=${MONGO_INITDB_ROOT_PASSWORD}
        - mongoApiPassword=${MONGO_API_PASSWORD}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - "27017"
    volumes:
      - /opt/lexio/prod/lexio-purchase-mongo/db:/data/db

  # Microservice for the purchase
  # =============================
  lexio-purchase:
    container_name: lexio-purchase
    image: lexio/lexio-purchase:0.2.5
    build: ../lexio-purchase
    environment:
      NODE_ENV: production
      MONGO_API_PASSWORD: ${MONGO_API_PASSWORD}
      API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "3010"
    links:
      - lexio-purchase-mongo:mongohost

  # Mongo Database for the game
  # ===============================
  lexio-game-mongo:
    container_name: lexio-game-mongo
    image: lexio/lexio-game-mongo:latest
    env_file: .env
    command: --auth
    build:
      context: ./lexio-game-mongo
      args: # used by setup.js
        - mongoInitDbRootUsername=${MONGO_INITDB_ROOT_USERNAME}
        - mongoInitDbRootPassword=${MONGO_INITDB_ROOT_PASSWORD}
        - mongoApiPassword=${MONGO_API_PASSWORD}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - "27017"
    volumes:
      - /opt/lexio/prod/lexio-game-mongo/db:/data/db

  # Microservice for the game
  # =============================
  lexio-game:
    container_name: lexio-game
    image: lexio/lexio-game:1.5.1
    build: ../lexio-game
    environment:
      NODE_ENV: production
      MONGO_API_PASSWORD: ${MONGO_API_PASSWORD}
      API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "3010"
    links:
      - lexio-game-mongo:mongohost

  # Mongo Database for the authentication
  # ===============================
  lexio-authentication-mongo:
    container_name: lexio-authentication-mongo
    image: lexio/lexio-authentication-mongo:latest
    env_file: .env
    command: --auth
    build:
      context: ./lexio-authentication-mongo
      args: # used by setup.js
        - mongoInitDbRootUsername=${MONGO_INITDB_ROOT_USERNAME}
        - mongoInitDbRootPassword=${MONGO_INITDB_ROOT_PASSWORD}
        - mongoApiPassword=${MONGO_API_PASSWORD}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - "27017"
    volumes:
      - /opt/lexio/prod/lexio-authentication-mongo/db:/data/db

  # Microservice for the authentication
  # =============================
  lexio-authentication:
    container_name: lexio-authentication
    image: lexio/lexio-authentication:0.8.1
    build: ../lexio-authentication
    environment:
      NODE_ENV: production
      MONGO_API_PASSWORD: ${MONGO_API_PASSWORD}
      API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
      API_FACEBOOK_USER_PASSWORD: ${API_FACEBOOK_USER_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "3010"
    links:
      - lexio-authentication-mongo:mongohost


  # Microservice for the gateway
  # ========================
  lexio-gateway:
    container_name: lexio-gateway
    image: lexio/lexio-gateway:0.2.0
    build: ../lexio-gateway
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "443:3000"
    volumes:
      - /etc/letsencrypt/archive/api.lexiogame.com:/var/app/ssl

  # Cron Service
  # ============
  lexio-cron:
    container_name: lexio-cron
    image: lexio/lexio-cron:0.4.4
    build: ../lexio-cron
    environment:
      NODE_ENV: production
      MONGO_API_PASSWORD: ${MONGO_API_PASSWORD}
      AUTHENTICATION_API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
    links:
      - lexio-authentication-mongo:mongohost
